Repository CMU-313/fall22-hw3-section-h-team-2, pull requests merged in 2022-10, with the labels that each got.

#7 Add functionality to assign reviewers
  docs-core/src/main/java/com/sismics/docs/core/dao/TagDao.java
  docs-web/src/main/java/com/sismics/docs/rest/resource/TagResource.java
Labels: enhancement

#9 adding functionality for reviewer boolean
  docs-core/src/main/java/com/sismics/docs/core/dao/TagDao.java
  docs-core/src/main/java/com/sismics/docs/core/dao/dto/TagDto.java
  docs-core/src/main/java/com/sismics/docs/core/dao/dto/UserDto.java
Labels: enhancement

#10 Changed all instances of "Tags" to "Reviewers"
  docs-web/src/main/webapp/src/locale/en.json
Labels: enhancement, help wanted

#11 Added skills, experience, and GPA attributes to relevant Document Daos.
  docs-core/src/main/java/com/sismics/docs/core/dao/DocumentDao.java
  docs-core/src/main/java/com/sismics/docs/core/dao/dto/DocumentDto.java
  docs-core/src/main/java/com/sismics/docs/core/model/jpa/Document.java
  docs-web/src/main/java/com/sismics/docs/rest/resource/DocumentResource.java
Labels: enhancement

#13 Create README_feature.md
  README_feature.md
Labels: documentation

#14 Reviewers page
  docs-web/src/main/java/com/sismics/docs/rest/resource/TagResource.java
Labels: enhancement

#17 Final merge for reviewers feature in homework 3
  README_feature.md
  docs-core/src/main/java/com/sismics/docs/core/dao/DocumentDao.java
  docs-core/src/main/java/com/sismics/docs/core/dao/TagDao.java
  docs-core/src/main/java/com/sismics/docs/core/dao/dto/DocumentDto.java
  docs-core/src/main/java/com/sismics/docs/core/dao/dto/TagDto.java
  docs-core/src/main/java/com/sismics/docs/core/dao/dto/UserDto.java
  docs-core/src/main/java/com/sismics/docs/core/model/jpa/Document.java
  docs-core/src/main/resources/config.properties
  docs-core/src/main/resources/db/update/dbupdate-028-0.sql
  docs-web/src/dev/resources/config.properties
  docs-web/src/main/java/com/sismics/docs/rest/resource/DocumentResource.java
  docs-web/src/main/java/com/sismics/docs/rest/resource/TagResource.java
  docs-web/src/main/webapp/src/locale/en.json
  docs-web/src/main/webapp/src/partial/docs/document.default.html
  docs-web/src/main/webapp/src/partial/docs/document.edit.html
  docs-web/src/prod/resources/config.properties
  docs-web/src/test/java/com/sismics/docs/rest/TestAppResource.java
  docs-web/src/test/java/com/sismics/docs/rest/TestDocumentResource.java
Labels: enhancement
